version: '3'

services:
  tesseract-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=yourDatabaseURL
      - DATABASE_PORT=yourDatabasePort
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
